//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Offwind.Products.Sowfa.Defaults {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WindPlantDefaultsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindPlantDefaultsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Offwind.Products.Sowfa.Defaults.WindPlantDefaultsRes", typeof(WindPlantDefaultsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_ABLProperties {
            get {
                return ResourceManager.GetString("constant_ABLProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_Cylinder1 {
            get {
                return ResourceManager.GetString("constant_airfoil_Cylinder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_Cylinder2 {
            get {
                return ResourceManager.GetString("constant_airfoil_Cylinder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_DU21_A17 {
            get {
                return ResourceManager.GetString("constant_airfoil_DU21_A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_DU25_A17 {
            get {
                return ResourceManager.GetString("constant_airfoil_DU25_A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_DU30_A17 {
            get {
                return ResourceManager.GetString("constant_airfoil_DU30_A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_DU35_A17 {
            get {
                return ResourceManager.GetString("constant_airfoil_DU35_A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_DU40_A17 {
            get {
                return ResourceManager.GetString("constant_airfoil_DU40_A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_airfoil_NACA64_A17 {
            get {
                return ResourceManager.GetString("constant_airfoil_NACA64_A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../precursorABL/neutral/boundaryData.
        /// </summary>
        public static string constant_boundaryData {
            get {
                return ResourceManager.GetString("constant_boundaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.1.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_cellDecomposition {
            get {
                return ResourceManager.GetString("constant_cellDecomposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_transportProperties {
            get {
                return ResourceManager.GetString("constant_transportProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_turbine_NREL5MWRef {
            get {
                return ResourceManager.GetString("constant_turbine_NREL5MWRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string constant_turbineArrayProperties {
            get {
                return ResourceManager.GetString("constant_turbineArrayProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_changeDictionaryDict {
            get {
                return ResourceManager.GetString("system_changeDictionaryDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_controlDict {
            get {
                return ResourceManager.GetString("system_controlDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_controlDict1 {
            get {
                return ResourceManager.GetString("system_controlDict1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_decomposeParDict {
            get {
                return ResourceManager.GetString("system_decomposeParDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_fvSchemes {
            get {
                return ResourceManager.GetString("system_fvSchemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_mapFieldsDict {
            get {
                return ResourceManager.GetString("system_mapFieldsDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_refineMeshDict {
            get {
                return ResourceManager.GetString("system_refineMeshDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_refineMeshDict_global {
            get {
                return ResourceManager.GetString("system_refineMeshDict_global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_refineMeshDict_local_1 {
            get {
                return ResourceManager.GetString("system_refineMeshDict_local_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_refineMeshDict_local_2 {
            get {
                return ResourceManager.GetString("system_refineMeshDict_local_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.0                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_refineMeshDict_local_3 {
            get {
                return ResourceManager.GetString("system_refineMeshDict_local_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_setFieldsABLDict {
            get {
                return ResourceManager.GetString("system_setFieldsABLDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_topoSetDict {
            get {
                return ResourceManager.GetString("system_topoSetDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  1.7.1                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.com                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_topoSetDict_global {
            get {
                return ResourceManager.GetString("system_topoSetDict_global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_topoSetDict_local_1 {
            get {
                return ResourceManager.GetString("system_topoSetDict_local_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_topoSetDict_local_2 {
            get {
                return ResourceManager.GetString("system_topoSetDict_local_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string system_topoSetDict_local_3 {
            get {
                return ResourceManager.GetString("system_topoSetDict_local_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string time_pd {
            get {
                return ResourceManager.GetString("time_pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string time_T {
            get {
                return ResourceManager.GetString("time_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0.x                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string time_U {
            get {
                return ResourceManager.GetString("time_U", resourceCulture);
            }
        }
    }
}
