//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Offwind.OpenFoam.Sintef.BoundaryFields {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoundaryFieldsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoundaryFieldsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Offwind.OpenFoam.Sintef.BoundaryFields.BoundaryFieldsRes", typeof(BoundaryFieldsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.1.1                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateEpsilon {
            get {
                return ResourceManager.GetString("TemplateEpsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.1.1                                 |
        ///|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateK {
            get {
                return ResourceManager.GetString("TemplateK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                |                                                  |
        ///| \\      /  F ield        | OpenFOAM:            The Open Source CFD Toolbox |
        ///|  \\    /   O peration    | Version:             1.5                         |
        ///|   \\  /    A nd          | Web:                 http://www.OpenFOAM.org     |
        ///|    \\/     M anipulation | Discretizer - Setup: http://www.discretizer.org  |
        ///\*------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateP {
            get {
                return ResourceManager.GetString("TemplateP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                |                                                  |
        ///| \\      /  F ield        | OpenFOAM:            The Open Source CFD Toolbox |
        ///|  \\    /   O peration    | Version:             1.5                         |
        ///|   \\  /    A nd          | Web:                 http://www.OpenFOAM.org     |
        ///|    \\/     M anipulation | Discretizer - Setup: http://www.discretizer.org  |
        ///\*------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateR {
            get {
                return ResourceManager.GetString("TemplateR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                |                                                  |
        ///| \\      /  F ield        | OpenFOAM:            The Open Source CFD Toolbox |
        ///|  \\    /   O peration    | Version:             1.5                         |
        ///|   \\  /    A nd          | Web:                 http://www.OpenFOAM.org     |
        ///|    \\/     M anipulation | Discretizer - Setup: http://www.discretizer.org  |
        ///\*------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateU {
            get {
                return ResourceManager.GetString("TemplateU", resourceCulture);
            }
        }
    }
}
