//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Offwind.OpenFoam.Models.TurbineArrayProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TurbineArrayPropRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TurbineArrayPropRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Offwind.OpenFoam.Models.TurbineArrayProperties.TurbineArrayPropRes", typeof(TurbineArrayPropRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({[[turnine_id]]})
        ///{
        ///    turbineType         &quot;({[[turbineType]]})&quot;;
        ///    baseLocation        (({[[x]]}) ({[[y]]}) ({[[z]]}));
        ///    numBladePoints      ({[[numBladePoints]]});
        ///    pointDistType       &quot;({[[pointDistType]]})&quot;;
        ///    pointInterpType     &quot;({[[pointInterpType]]})&quot;;
        ///    bladeUpdateType     &quot;({[[bladeUpdateType]]})&quot;;
        ///    epsilon              ({[[epsilon]]});
        ///    tipRootLossCorrType &quot;({[[tipRootLossCorrType]]})&quot;;
        ///    rotationDir         &quot;({[[rotationDir]]})&quot;;
        ///    Azimuth              ({[[Azim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateArray {
            get {
                return ResourceManager.GetString("TemplateArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*--------------------------------*- C++ -*----------------------------------*\
        ///| =========                 |                                                 |
        ///| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
        ///|  \\    /   O peration     | Version:  2.0                                   |
        ///|   \\  /    A nd           | Web:      http://www.OpenFOAM.org               |
        ///|    \\/     M anipulation  |                                                 |
        ///\*------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateGlob {
            get {
                return ResourceManager.GetString("TemplateGlob", resourceCulture);
            }
        }
    }
}
