//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Offwind.Products.WakeModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WakeModelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WakeModelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Offwind.Products.WakeModel.WakeModelRes", typeof(WakeModelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000    The number of grid points in x direction
        ///1000    The number of the grid points in Y direction
        ///50     THE DIAMETER OF THE TURBINE
        ///70      THE HEIGHT OF THE TURBINE
        ///0.5     THE HUB THRUST COEFFICIENT OF TURBINE
        ///0.02     THE WAKE DECAY CONSTANT
        ///9.    m/s - VELOCITY AT THE HUB, WITHOUT THE INFLUENCE OF THE WIND TURBINE
        ///48       THE NUMBER OF THE TURBINE
        ///1.225     THE DENSITY OF THE AIR AROUNT TURBINE
        ///0.2
        ///-48.4          rotation angle - clockwise - in grade
        ///
        ///X            Y   THE COORDINATE OF THE CENTER  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({[[GridPointsX]]})    The number of grid points in x direction
        ///({[[GridPointsY]]})    The number of the grid points in Y direction
        ///({[[TurbineDiameter]]})     THE DIAMETER OF THE TURBINE
        ///({[[TurbineHeight]]})      THE HEIGHT OF THE TURBINE
        ///({[[HubThrust]]})     THE HUB THRUST COEFFICIENT OF TURBINE
        ///({[[WakeDecay]]})     THE WAKE DECAY CONSTANT
        ///({[[VelocityAtHub]]})    m/s - VELOCITY AT THE HUB, WITHOUT THE INFLUENCE OF THE WIND TURBINE
        ///({[[TurbinesAmount]]})       THE NUMBER OF THE TURBINE
        ///({[[AirDensity]] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string initial_data_inp {
            get {
                return ResourceManager.GetString("initial_data_inp", resourceCulture);
            }
        }
    }
}
